services:
  postgresql:
    image: postgres:latest
    volumes:
      - ./env/volume:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_MULTIPLE_DATABASES: stakfin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSRTGRES_DB: admin
    ports:
     - 5432:5432