server:
  port: 8080

spring:
  application:
    name: api-gateway

# swagger-ui custom path
springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs


management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: "*"
