server:
  port: 8081

logging:
  level:
    root: INFO

spring:
  application:
    name: api-stakfin-core
  datasource:
    url: jdbc:postgresql://localhost:5432/stakfin_db
    username: stakfin_user
    password: stakfin
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# swagger-ui custom path
springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger/swagger-ui
  api-docs:
    path: /swagger/api-docs

# Actuator
management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: "*"